### ISSUE TITLE
优化之预请求

### ISSUE THREAD

**Issue by wangjing013** [wangjing013/blog#47]
##  预解析

链接预取是一种浏览器机制, 其利用浏览器空闲时间来下载或预取用户在不久的将来可能访问的文档. 网页向浏览器提供一组预取提示, 并在浏览器完成当前页面的加载后开始静默地拉取指定的文档并将其存储在缓存中.  当用户访问其中一个预取文档时, 便可以快速的从浏览器缓存中得到.

*  DNS Prefetching

DNS-prefetch (DNS 预获取) 是尝试在请求资源之前解析域名。这可能是后面要加载的文件，也可能是用户尝试打开的链接目标
```js
<link rel="dns-prefetch" href="//shiguangkey.com">
```

为什么使用 ``dns-prefetch`` ?

参考[浏览器输入URL 后发生了什么?](https://github.com/wangjing013/blog/issues/45)文章, 当从浏览器发送请求时,  必须先将该跨域域名解析为 IP 地址, 然后浏览器才能发出请求.  此过程称为 DNS 解析.  

*  Preconnect

当使用 ``preconnect`` 时,  浏览器将尝试去初始化连接和完成连接握手.  针对不同请求协议做的事情不一样.

* ``http ``  时会尝试进行： DNS + TCP.
* ``https`` 时会尝试进行:    DNS + TCP + TLS

```js
<link rel="preconnect" href="//example.com">
<link rel="preconnect" href="//cdn.example.com" crossorigin>
```
预连接初始化, 大概的步骤如下:

* 通过 href 属性提供 URL 进行查找
    * 如果 ``URL scheme`` 不是 ``http`` 或 ``https`` 时,则终止其它步骤执行.  
* 把 ``URL origin`` 作为预连接的 ``origin``
* ``corsAttributeState`` 属性值表示Link元素 [``crossorigin``](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Attributes/crossorigin) 属性值.
* 把 ``credentials`` 属性设置为 ``true``
* 如果 ``corsAttributeState`` 值为 ``anonymous `` 并且 ``origin`` 不等于当前文档的 ``origin``. 则会把 ``credentials`` 设置为 ``false``
* 尝试基于 ``origin`` 建立连接和获取凭着.

*  Prefetching

当 link 属性 ``rel`` 值为 Prefetching 时, 表示当前资源可能下一个导航时需要,  告诉客户端需要去提前请求.
这样客户端在将来请求资源时提供更快的响应.
```js
<link rel="prefetch" href="//example.com/next-page.html" as="document" crossorigin="use-credentials">
<link rel="prefetch" href="/library.js" as="script">
```

常见的一些用途, 预请求背景图片 如下:
```css
.page--home         { background-image:url(home.jpg); }
.page--about        { background-image:url(about.jpg); }
.page--portfolio    { background-image:url(portfolio.jpg); }
.page--contact      { background-image:url(contact.jpg); }
```
可以通过 ``prefetch `` 预加载图片, 无需等待CSS文件被解析时再去加载.
```js
<link rel="prefetch" href="sprite.png">
```

*  Prerender

当 link 属性 ``rel`` 值为 Prerender 时, 表示当前资源可能下一个导航时需要,  告诉客户端需要去提前请求并执行.  这样客户端在将来请求资源时提供更快的响应.
```js
<link rel="prerender" href="//example.com/next-page.html">
```

## 总结
具体采用那种方式可以根据具体业务场景使用.
